### ISSUE TITLE
Infografia de Hilos

### ISSUE THREAD

**Issue by AdriHernandez-Martinez08** [SistemasTecTlaxiaco/infografia-de-hilos-AdriHernandez-Martinez08#3]
[Infografía-Hilos .pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-AdriHernandez-Martinez08/files/15049703/Infografia-Hilos.pdf)

**Comment by Ariadnamonserrat10** [comment]
Calificación
20 de 20 cumple con la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
